"""Writes v1.3/TIMING-part2.md, part 2's shot list, from cues-part2.json and part 1's length.
   python3 v1.3/shots.py"""
import json
import os

here = os.path.dirname(os.path.abspath(__file__))
c = json.load(open(os.path.join(here, 'cues-part2.json')))
P1 = 1780 / 60   # part 1: v1.1's 30 s cut, 1780 frames
C, dur = c['cues'], c['dur']
play = next(s for s in c['timeline'] if s['k'] == 'play')
J = play['t0']
FRAMING = {'whole': 'the whole page', 'lock': 'close on the lockup (part 1: the seals stamped)', 'nav': 'the nav, where part 1\'s desk lands',
           'card': 'the board\'s lead card (part 1: the card into your hand)', 'notes': 'the field notes (part 1: the dossier)',
           'tabs': 'the chapter links (part 1: #35\'s tabs)', 'print': 'the print (part 1: peg and all)', 'homeLink': 'the home link, then the desk'}
keys = [x for x in C if x['type'] == 'frame']
# a shot is the camera travelling to a framing and holding it until it leaves
shots, i = [], 0
while i < len(keys):
    k = keys[i]; j = i
    while j + 1 < len(keys) and keys[j + 1]['name'] == k['name']: j += 1
    shots.append((k['name'], k['t'], keys[j]['t'])); i = j + 1
end0 = next(x['t'] for x in C if x['type'] == 'putback')
rows = [(0, 1.3, 'the join', 'part 1\'s last sheet pulled aside to the left; the take already loading under it; 「#17 之前 · BEFORE」 stamped in its top margin at %.2f' % next(x['t'] for x in C if x['type'] == 'label'), 'the pull, the stamp')]
prev = 1.3
for n, (name, a, b) in enumerate(shots):
    nxt = shots[n + 1][1] if n + 1 < len(shots) else end0
    beats = [x for x in C if x['type'] == 'site' and prev <= x['t'] < nxt]
    what = '; '.join(f"{x['what']} ({x['t']:.2f})" for x in beats) or ('the old home: its loading screen, its iris, the desk' if name == 'whole' and a < 5 else 'held')
    snd = ', '.join('click + cut' if x['kind'] == 'nav' or x['name'] in ('click-book', 'take-card', 'open-print') else 'click' for x in beats if x['kind'] in ('click', 'nav'))
    rows.append((prev, nxt, FRAMING[name], what, snd)); prev = nxt
rows.append((end0, dur, 'the end', 'the last sheet put back from the left (a chapter before this one), landing on part 1\'s last frame', 'the put-back, the tonic'))
out = ['# v1.3 · part 2 shot list', '',
       f'Generated by `shots.py` from `cues-part2.json`. Part 2 runs {dur:.2f} s; in the combined file it starts at {P1:.2f} (part 1 is v1.1\'s 30 s cut, 1780 frames). One camera, no cuts: each row runs from the camera\'s arrival at a framing (part 1\'s for the same beat) to its arrival at the next. Under all of it, the sparse bed (`score.py`). The take (footage) is part 2 time − {J:.2f} s, in real time throughout.', '',
       '| part 2 | combined | the take | framing | what happens (part 2 time) | sound |', '|---|---|---|---|---|---|']
for a, b, name, what, snd in rows:
    u = f'{max(0, a - J):.2f}–{min(play["u1"], b - J):.2f}' if b > J and a < end0 else ''
    out.append(f'| {a:.2f}–{b:.2f} | {P1 + a:.2f}–{P1 + b:.2f} | {u} | {name} | {what} | {snd} |')
open(os.path.join(here, 'TIMING-part2.md'), 'w').write('\n'.join(out) + '\n')
print('\n'.join(out))
