// Generated by scripts/generate-content.py; edit the canonical content sources instead.
window.FY_HOME={"essays":27,"photos":107,"post":{"id":"2026-08-29_google-just-wants-to-coast-to-a-win","date":"2026-08-29","title":"Google Just Wants to Coast to a Win","titleZh":"谷歌只想躺赢"},"photo":{"id":108,"loc":"New Orleans, LA","date":"2025-11-27"}};
