"""Writes v1.5/TIMING.md from cues-promo.json and cues-part2.json: every shot on the film's clock (and its take), each
ramp's speeds, each caption against its motion, and part 2's shot list.   python3 v1.5/timing.py"""
import json
import os

here = os.path.dirname(os.path.abspath(__file__))
c1, c2 = (json.load(open(os.path.join(here, n))) for n in ('cues-promo.json', 'cues-part2.json'))
tc = lambda t: f'{int(t // 60)}:{t % 60:05.2f}'
C, TL, D1 = c1['cues'], c1['timeline'], c1['dur']
WORDS = {'desk': '桌子变成了导航 · the desk becomes the nav', 'tabs': '标签跟着你走 · the tabs travel with you',
         'develop': '照片在绳上慢慢显影 · the prints develop on their lines', 'print': '连夹子一起取下 · unclipped, peg and all',
         'card': '从封套里抽出，再翻过来 · out of its sleeve, then turned over', 'home': '导航落回桌上 · the nav falls back into a desk'}
WHAT = {'': 'home, a first visit: the OP, the motto, the seals (close on the lockup from 3.3)', 'desk': 'the book: the desk flies up into the nav',
        'tabs': 'the card into your hand, the dossier; 03: #35\'s tabs fly to the chapter\'s fore-edge',
        'home': 'the board → the shooting tab\'s move, the prints develop on their lines → a print out with its peg, and back → the about tab\'s move → the specimen card out of its sleeve, turned over → home: the nav falls back into a desk'}
out = ['# v1.5 · timing', '', f'Generated by `timing.py` from `cues-promo.json` and `cues-part2.json`. Part 1 runs {tc(D1)}, part 2 {tc(c2["dur"])}, together {tc(D1 + c2["dur"])}, at 60 fps.', '',
       '## Part 1, the promo', '', '| film time | take | shot | footage (s) | speed | the site\'s clicks |', '|---|---|---|---|---|---|']
for s in TL:
    a, b = tc(s['t0']), tc(s['t1'])
    if s['k'] == 'play':
        spd = 'real time'
        if 'ramp' in s:
            r = s['ramp']; rc = next(x for x in C if x['type'] == 'ramp' and x['name'] == s['name'])
            spd = (f"real time to {r['a']:.3f}; eased down to ⅓ over {r['Ti']:.2f} s, ⅓ for {r['Th']:.2f} s ({tc(rc['slow'][0])}–{tc(rc['slow'][1])}), "
                   f"eased back up over {r['To']:.2f} s by {r['d']:.3f}; real time after")
        snd = ', '.join(x['name'] for x in C if x['type'] == 'site' and x['kind'] in ('click', 'nav', 'drag') and s['t0'] <= x['t'] < s['t1'])
        out.append(f"| {a}–{b} | {s['take']} | {WHAT[s['name']]} | {s['u0']:.2f}–{s['u1']:.2f} | {spd} | {snd or 'none'} |")
    elif s['k'] == 'jump':
        out.append(f"| {a}–{b} | | the sheet in front pulled aside to the left; the next moment already under it, both still playing | | | |")
    else:
        land = next(x['t'] for x in C if x['type'] == 'landed')
        out.append(f"| {a}–{b} | | the take pulled aside; the last sheet: 继续写，继续造 written, the seals stamped, the two credits stamped as the dossier stamps its facts (the last lands {tc(land)}, held {D1 - land:.2f} s) | | | |")
out += ['', '### Captions against their motions', '', '| caption | fully on screen | motion | in before it | still in after it | fully visible |', '|---|---|---|---|---|---|']
for k in (x for x in C if x['type'] == 'caption'):
    f0, f1 = k['t'] + .2, k['t'] + k['dur'] - .2; m0, m1 = k['motion']
    out.append(f"| {WORDS[k['name']]} | {tc(f0)}–{tc(f1)} | {tc(m0)}–{tc(m1)} | {m0 - f0:.2f} s | {f1 - m1:.2f} s | {f1 - f0:.2f} s |")
# part 2: the camera's framings
C2 = c2['cues']
keys = [x for x in C2 if x['type'] == 'frame']
shots, i = [], 0
while i < len(keys):
    j = i
    while j + 1 < len(keys) and keys[j + 1]['name'] == keys[i]['name']: j += 1
    shots.append((keys[i]['name'], keys[i]['t'])); i = j + 1
e0 = next(x['t'] for x in C2 if x['type'] == 'putback')
out += ['', '## Part 2, the before (starts at ' + tc(D1) + ' in film-v1.5.mp4)', '', '| part 2 | combined | framing | what happens |', '|---|---|---|---|',
        f"| 0:00.00–0:01.30 | {tc(D1)}–{tc(D1 + 1.3)} | the join | part 1's last sheet pulled aside; the take already loading under it; 「#17 之前 · BEFORE」 fully in the strip at 0:00.80 |"]
prev = 1.3
for n, (name, a) in enumerate(shots):
    nxt = shots[n + 1][1] if n + 1 < len(shots) else e0
    beats = '; '.join(f"{x['what']} ({tc(x['t'])})" for x in C2 if x['type'] == 'site' and prev <= x['t'] < nxt) or 'held'
    out.append(f'| {tc(prev)}–{tc(nxt)} | {tc(D1 + prev)}–{tc(D1 + nxt)} | {name} | {beats} |'); prev = nxt
out.append(f"| {tc(e0)}–{tc(c2['dur'])} | {tc(D1 + e0)}–{tc(D1 + c2['dur'])} | the end | the label out; the last sheet put back from the left, landing on part 1's last frame |")
open(os.path.join(here, 'TIMING.md'), 'w').write('\n'.join(out) + '\n')
print('wrote TIMING.md', len(out), 'lines')
