"""The rough cut's timing sheet, from rough/cues.json: every shot, every live-footage placement, every time the page
is lifted to show the site before #17, and every sound cue, on the film's clock.
   python3 rough/timing.py  → rough/TIMING.md"""
import json
import os

here = os.path.dirname(__file__)
c = json.load(open(os.path.join(here, 'cues.json')))
TL, C, DUR = c['timeline'], c['cues'], c['dur']
tc = lambda t: f'{int(t // 60)}:{t % 60:05.2f}'
rows = ['| film time | shot | on the sheet (live, real input) | the page under it (before, 6237120) | sound |', '|---|---|---|---|---|']
rows.append(f'| {tc(0)}–{tc(TL[0]["t0"])} | the closed dossier; the cover opens on its hinge | | | paper, the cover landing |')
for i, s in enumerate(TL):
    beats = [x for x in C if x.get('session') == s['name'] and x['type'] == 'site']
    lifts = [x for x in C if x.get('session') == s['name'] and x['type'] in ('lift', 'drop')]
    rows.append(f'| **{tc(s["t0"])}–{tc(s["t1"])}** | **sheet {i + 1}: `{s["name"]}`** ({s["t1"] - s["t0"]:.1f} s, one continuous recording) | frames 1–{round((s["t1"] - s["t0"]) * 30)} of `after/` | frames 1–{round((s["t1"] - s["t0"]) * 30)} of `before/`, same input, same moment | the sheet\'s music section |')
    ev = sorted(beats + lifts, key=lambda x: x['t'])
    for x in ev:
        if x['type'] == 'site':
            rows.append(f'| {tc(x["t"])} | | {x["name"]}: {x.get("what", "")} ({x.get("kind", "")}) | | {x.get("kind", "")} |')
        elif x['type'] == 'lift':
            rows.append(f'| {tc(x["t"])} | the page is lifted | | **shown**, at the same moment ({x.get("at", "")}) | paper up |')
        else:
            rows.append(f'| {tc(x["t"])} | the page falls back | | covered | paper, a soft slap |')
    nxt = TL[i + 1]['t0'] if i + 1 < len(TL) else None
    rows.append(f'| {tc(s["t1"])}–{tc(nxt if nxt else s["t1"] + 1.5)} | the sheet is pulled aside to the left (#35\'s chapter move){"; the next is already there" if nxt else "; the folder is empty"} | | | a long paper whoosh |')
end = [x for x in C if x['type'] in ('motto', 'stamp', 'type')]
if end:
    rows.append(f'| {tc(end[0]["t"])}–{tc(DUR)} | the folder\'s back: the motto written with the lockup\'s strokes, the two seals stamped, the credits typed | | | the pen alone, two stamps on the tonic, typing, the last note rings |')
open(os.path.join(here, 'TIMING.md'), 'w').write(f'# Rough cut · timing sheet\n\nGenerated by `timing.py` from `cues.json`. Total {tc(DUR)} at 30 fps.\n\n' + '\n'.join(rows) + '\n')
print('wrote TIMING.md', len(rows), 'rows')
