"""v1's timing sheet, from v1/cues.json: every shot (film time → footage time), every lift and what the site before
#17 does under it, every replay, the pen's names and notes, and the sound cues.
   python3 v1/timing.py [cues.json] [out.md]"""
import json
import os
import sys

here = os.path.dirname(__file__)
src = sys.argv[1] if len(sys.argv) > 1 else os.path.join(here, 'cues.json')
out = sys.argv[2] if len(sys.argv) > 2 else os.path.join(here, 'TIMING.md')
c = json.load(open(src))
TL, C, DUR = c['timeline'], c['cues'], c['dur']
tc = lambda t: f'{int(t // 60)}:{t % 60:05.2f}'
WHAT = {
    'cover': 'the closed dossier ("改版 · The redesign"); the cover opens on its hinge and the OP starts as it lands',
    'end': 'the take pulled aside to the left; the last sheet: 继续写，继续造 written with the lockup\'s strokes, the seals stamped, the credits by line',
    'jump': 'the sheet in front pulled aside to the left; the next moment of the take is already under it',
}
rows = ['| film time | shot | the take (footage s) | under the page (the site before #17) | sound |', '|---|---|---|---|---|']
for s in TL:
    k, a, b = s['k'], s['t0'], s['t1']
    if k == 'play':
        beats = [x for x in C if x['type'] == 'site' and s['u0'] <= x.get('u', -1) < s['u1']]
        rows.append(f'| {tc(a)}–{tc(b)} | the take, real time | {s["u0"]:.2f}–{s["u1"]:.2f} | | the site\'s own foley |')
        for x in beats: rows.append(f'| {tc(x["t"])} | | {x["name"]}: {x.get("what", "")} | | {x.get("kind", "")} |')
    elif k == 'lift':
        rows.append(f'| **{tc(a)}–{tc(b)}** | **the page lifted: {s["name"]}** | held at {s["at"]:.2f} (its click is next) | **the same click on 6237120**, its hard cut, from {s["at"]:.2f} | paper, 8–10 dB under; the bed ducked 6 dB under the cut |')
    elif k == 'replay':
        rows.append(f'| {tc(a)}–{tc(b)} | **×⅓ replay**, true 180 fps frames | {s["u0"]:.2f}–{s["u1"]:.2f} | | one held note |')
    else:
        rows.append(f'| {tc(a)}–{tc(b)} | {WHAT.get(k, k)} | | | |')
chap = [x for x in C if x['type'] == 'chapter']
rows.append('')
rows.append('Chapter names, written by the pen in the top margin: ' + '; '.join(f'{tc(x["t"])} {x["name"]}' for x in chap) + '.')
open(out, 'w').write(f'# The film v1 · timing sheet\n\nGenerated by `timing.py` from `{os.path.basename(src)}`. Total {tc(DUR)} at 60 fps.\n\n' + '\n'.join(rows) + '\n')
print('wrote', out, len(rows), 'rows')
